# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField()),
                ('cc', models.TextField(blank=True)),
                ('bcc', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('test', 'Test Name')], max_length=50, unique=True, verbose_name='type')),
                ('remarks', models.TextField(help_text='Extra information about the template', verbose_name='remarks')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='Add the body with {{variable}} placeholders', verbose_name='body')),
            ],
            options={
                'verbose_name': 'mail template',
                'verbose_name_plural': 'mail templates',
            },
        ),
    ]
