# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Extra information about the template', verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='template_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='type'),
        ),
    ]
