# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_editor', '0002_auto_20170227_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
