# Generated by Django 2.2.8 on 2020-04-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_editor", "0008_auto_20200416_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="base_template_path",
            field=models.CharField(
                blank=True,
                help_text="Leave empty for default template. Override to load a different template.",
                max_length=200,
                null=True,
                verbose_name="Base template path",
            ),
        ),
    ]
