# Generated by Django 2.2.8 on 2021-10-19 13:04

from django.db import migrations, models
import django.db.models.deletion

from werkbezoek.domains.models import Domain


def default_domain():
    domain = Domain.objects.first()
    return domain.pk if domain else None


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
        ("mail_editor", "0009_auto_20200416_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="domain",
            field=models.ForeignKey(
                default=default_domain,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mail_templates",
                to="domains.Domain",
                verbose_name="Domein",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="mailtemplate",
            unique_together={("template_type", "language", "domain")},
        ),
    ]
