# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_editor', '0009_auto_20200416_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='language',
            field=models.CharField(blank=True, choices=[(b'nl', 'Netherlands'), (b'en', 'English')], max_length=10, null=True),
        ),
    ]
