# Generated by Django 3.2 on 2021-05-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_editor", "0010_auto_20210422_1354"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mailtemplate",
            unique_together=set(),
        ),
    ]
