# Generated by Django 4.2 on 2024-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail_editor", "0013_alter_mailtemplate_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="domain_id",
            field=models.IntegerField(default=1),
        ),
    ]
