# Generated by Django 3.2 on 2023-10-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_editor', '0010_auto_20211019_1504'),
        ('mail_editor', '0013_alter_mailtemplate_language'),
    ]

    operations = [
    ]
